toolbox configured

diff --git a/vagrant/stationctl b/vagrant/stationctl
--- a/vagrant/stationctl
+++ b/vagrant/stationctl
@@ -1,6 +1,6 @@
 #!/bin/bash -eu
 
-# set -o pipefail
+set -o pipefail
 
 
 ###############################################################################
@@ -26,9 +26,13 @@ esac
 
 ELASTIC="ts.elastic"
 WINDOWS="ts.windows10"
-DEBIAN="ts.debian11"
-REDOPS="ts.redops"
+ROCKY="ts.rocky9"
+#REDOPS="ts.redops"
+DC="ts.dc"
 
+# other vars
+
+export $(cat .env | grep -v '^#')
 
 ############ dependency installs
 
@@ -69,7 +73,7 @@ main() {
         echo -e "${LIGHTPURPLE}  _\ \/ __/ _ \/ __/ / _ \/ _ \ ${NC}    Memory used: $MEM     ";
         echo -e "${LIGHTPURPLE} /___/\__/\_,_/\__/_/\___/_//_/ ${NC}    Disk usage.: $DISK    ";
         echo ""
-        echo -e "${LIGHTPURPLE}  ATTACK with Atomic <-----------> DETECT with Elastic${NC}"
+        echo -e "${LIGHTPURPLE}  ATTACK with Operator <-----------> DETECT with Elastic${NC}"
         echo -e "${LIGHTPURPLE} ------------------------------------------------------${NC}";
         echo -e ""
         echo -e " 1. Setup........:  install dependencies (${ORANGE}experimental${NC})"
@@ -256,7 +260,7 @@ setup_rhel() {
         echo -e "${LIGHTPURPLE}     (B)ack to Main                           ${NC}";
         echo -e "${LIGHTPURPLE} ---------------------------------------------${NC}";
         echo ""
-        echo -e " You have chosen a RHEL-based distro (preferrably \n Centos7) as your host Operating System. This option \n will attempt to install the required packages: "
+        echo -e " You have chosen a RHEL-based distro (preferrably \n CENTOS7) as your host Operating System. This option \n will attempt to install the required packages: "
         echo ""
         echo ""
         echo "  virtualbox.....:  hypervisor"
@@ -303,7 +307,7 @@ if [[ "${machine}" == "Linux" ]]; then
     RHELFAM="$(sed s/\"//g /etc/os-release | grep -e "^ID=")"
 
     if [ "${RHELFAM}" == "ID=centos" ]; then
-        DEBIAN_install
+        CENTOS_install
 
     elif [ "${RHELFAM}" == "ID=fedora" ]; then
         fedora_install
@@ -424,9 +428,12 @@ deploy_quick() {
         echo ""
         echo "    Windows 10..:  Windows target box"
         echo ""
-        echo "    DEBIAN 11....:  Linux target box"
+        echo "    Rocky 9....:  Linux target box"
         echo ""
-        echo "    Redops......:  Linux adversary box"
+        #echo "    Redops......:  Linux adversary box"
+        #echo ""
+        #echo ""
+        echo "In addition to the base emulation we can also install other tools. Please make changes to the ".env" file if you haven't."
         echo ""
         echo ""
         read -rp " Proceed to deploy this configuration? [Y/N]: " yn
@@ -438,7 +445,7 @@ deploy_quick() {
                 echo -e " ${LIGHTPURPLE}---------------------------------------------${NC}";
                 echo "";
                 echo "";
-                vagrant up "${ELASTIC}" "${WINDOWS}" "${DEBIAN}" "${REDOPS}"; sleep 5;
+                vagrant up "${ELASTIC}" "${WINDOWS}" "${ROCKY}"; sleep 5;
                 echo " Clearing any alerts that might have been generated by the agents.."
                 delete_signals;
                 sleep 2;
@@ -478,7 +485,7 @@ deploy_custom() {
         echo -e "${LIGHTPURPLE}     (B)ack to Main                           ${NC}";
         echo -e "${LIGHTPURPLE} ---------------------------------------------${NC}";
         echo ""
-        echo "The Elastic (control) box is required."
+        echo "The Elastic and Redops boxes are required."
         echo "What TARGET boxes would you like to deploy?"
         echo ""
         read -rp "Deploy the Windows10 target? [Y/N]: " yn
@@ -498,29 +505,10 @@ deploy_custom() {
         echo -e "${LIGHTPURPLE}     (B)ack to Main                           ${NC}";
         echo -e "${LIGHTPURPLE} ---------------------------------------------${NC}";
         echo ""
-        read -rp "Deploy the Debian11 target? [Y/N]: " yn
+        read -rp "Deploy the Rocky9 target? [Y/N]: " yn
         case $yn in
-            [Yy]* ) DEBIAN="ts.debian11"; break;;
-            [Nn]* ) DEBIAN=""; break;;
-            [Bb]* ) clear; deploy; break;;
-            * ) echo -e "\n${RED} Selection invalid, try again:${NC} "; sleep 2;;
-        esac
-    done
-    while true; do
-        clear
-        echo -e "${LIGHTPURPLE}      __________  ___           __            ${NC}";
-        echo -e "${LIGHTPURPLE}     /_  __/ __/ / _ \___ ___  / /__  __ __   ${NC}";
-        echo -e "${LIGHTPURPLE}      / / _\ \  / // / -_) _ \/ / _ \/ // /   ${NC}";
-        echo -e "${LIGHTPURPLE}     /_/ /___/ /____/\__/ .__/_/\___/\_, /    ${NC}";
-        echo -e "${LIGHTPURPLE}                       /_/          /___/     ${NC}";
-        echo -e "${LIGHTPURPLE}     (B)ack to Main                           ${NC}";
-        echo -e "${LIGHTPURPLE} ---------------------------------------------${NC}";
-        echo ""
-        read -rp "Deploy the Redops (redteam) adversary box? [Y/N]: " yn
-        case $yn in
-            [Yy]* ) REDOPS="ts.redops"; break;;
-            [Nn]* ) REDOPS=""; break;;
-            [Bb]* ) clear; deploy; break;;
+            [Yy]* ) ROCKY="ts.rocky9"; break;;
+            [Nn]* ) ROCKY=""; break;;
             * ) echo -e "\n${RED} Selection invalid, try again:${NC} "; sleep 2;;
         esac
     done
@@ -537,15 +525,16 @@ deploy_custom() {
         echo ""
         echo " You have chosen the following Custom Deployment:"
         echo ""
-        echo " - CONTROL..: "${ELASTIC}" (required)"
+        echo " - STACK..: "${ELASTIC}" (required)"
+        echo " - CONTROL...: "${REDOPS}" (required)"
         echo " - target...: "${WINDOWS}""
-        echo " - target...: "${DEBIAN}""
-        echo " - redops...: "${REDOPS}""
+        echo " - target...: "${ROCKY}""
         echo ""
         read -rp "Confirm to proceed with deployment [Y/N]: " yn
         case $yn in
             [Yy]* )
-                vagrant up "${ELASTIC}" "${WINDOWS}" "${DEBIAN}" "${REDOPS}";
+                echo "You have chosen the "${ELASTIC}" "${REDOPS}" "${WINDOWS}" "${ROCKY}""
+                vagrant up ${ELASTIC} ${REDOPS} ${WINDOWS} ${ROCKY};
                 sleep 10;
                 snapshot;
                 break;;
@@ -591,10 +580,10 @@ deploy_staged() {
         echo -e "${LIGHTPURPLE}     (B)ack to Main                           ${NC}";
         echo -e "${LIGHTPURPLE} ---------------------------------------------${NC}";
         echo ""
-        read -rp "  Pre-stage the Debian11 target? [Y/N]: " yn
+        read -rp "  Pre-stage the Rocky9 target? [Y/N]: " yn
         case $yn in
-            [Yy]* ) DEBIAN="ts.debian11"; break;;
-            [Nn]* ) DEBIAN=""; break;;
+            [Yy]* ) ROCKY="ts.rocky9"; break;;
+            [Nn]* ) ROCKY=""; break;;
             [Bb]* ) clear; deploy; break;;
             * ) echo -e "\n${RED} Selection invalid, try again:${NC} "; sleep 2;;
         esac
@@ -630,10 +619,10 @@ deploy_staged() {
         echo ""
         echo "  You have chosen to Pre-stage the following boxes:"
         echo ""
-        echo "  - CONTROL..: ${ELASTIC}"
+        echo "  - STACK..: ${ELASTIC}"
         echo "  - target...: ${WINDOWS}"
-        echo "  - target...: ${DEBIAN}"
-        echo "  - redops...: "${REDOPS}""
+        echo "  - target...: ${ROCKY}"
+        #echo "  - CONTROL...: "${REDOPS}""
         echo ""
         read -rp "  Confirm to proceed with pulling the above [Y/N]: " yn
         case $yn in
@@ -645,7 +634,7 @@ deploy_staged() {
                 echo -e "  ${LIGHTPURPLE}-----------------------------------${NC}";
                 echo ""
                 sleep 3
-                for machine in elastic windows10 debian11
+                for machine in elastic windows10 rocky9
                 do
                     vagrant box add -cf "thremulation-station/${machine}";
                 done
@@ -702,7 +691,7 @@ status() {
         echo "   Vagrant Box Status:"
         echo -e "   ${LIGHTPURPLE}------------------${NC}";
         echo ""
-        vagrant status "${ELASTIC}" "${WINDOWS}" "${DEBIAN}" "${REDOPS}"; sleep 2;
+        vagrant status "${ELASTIC}" "${WINDOWS}" "${ROCKY}"; sleep 2;
         echo ""
         echo ""
         echo "   Elasticsearch Cluster Status:"
@@ -759,7 +748,7 @@ delete_indexes() {
 }
 
 delete_signals() {
-    curl -H "Content-Type: application/json" -X POST "192.168.56.10:9200/.siem-signals-default-*/_delete_by_query" -d \
+    curl -H "Content-Type: application/json" -XPOST "https://192.168.56.10:9200/.siem-signals-default-*/_delete_by_query" -k -u vagrant:vagrant -d \
                 '{
                     "query": {
                         "match": {
@@ -832,7 +821,7 @@ manage() {
                 echo -e "  ${LIGHTPURPLE}-----------------------------------${NC}";
                 echo ""
                 echo ""
-                vagrant suspend "${ELASTIC}" "${WINDOWS}" "${DEBIAN}" "${REDOPS}"; # Added names because on windows leaving this blank does not work
+                vagrant suspend "${ELASTIC}" "${WINDOWS}" "${ROCKY}"; # Added names because on windows leaving this blank does not work
                 echo ""
                 echo ""
                 read -rp " (B)ack or (M)ain Menu: " yn
@@ -868,7 +857,7 @@ manage() {
                 echo -e "  ${LIGHTPURPLE}-----------------------------------${NC}";
                 echo ""
                 echo ""
-                vagrant reload --no-provision "${ELASTIC}" "${WINDOWS}" "${DEBIAN}" "${REDOPS}";
+                vagrant reload --no-provision "${ELASTIC}" "${WINDOWS}" "${ROCKY}";
                 echo ""
                 echo ""
                 read -rp " (B)ack or (M)ain Menu: " yn
@@ -956,7 +945,7 @@ manage() {
                 sleep 5;
                 echo -e "  ${LIGHTPURPLE}-----------------------------------${NC}";
                 echo ""
-                vagrant destroy -f "${ELASTIC}" "${WINDOWS}" "${DEBIAN}" "${REDOPS}";
+                vagrant destroy -f "${ELASTIC}" "${WINDOWS}" "${ROCKY}";
                 echo "";
                 echo "";
                 echo "  All VMs deleted! Returning to Menu";
@@ -1018,7 +1007,7 @@ resume() {
                 echo ""
                 echo ""
                 sleep 3;
-                vagrant resume  --no-provision "${ELASTIC}" "${WINDOWS}" "${DEBIAN}" "${REDOPS}";
+                vagrant resume  --no-provision "${ELASTIC}" "${WINDOWS}" "${ROCKY}";
                 sleep 1;
                 echo ""
                 echo ""
@@ -1067,10 +1056,10 @@ resume_custom() {
         echo -e "${LIGHTPURPLE}     (B)ack to Main                               ${NC}";
         echo -e "${LIGHTPURPLE} -------------------------------------------------${NC}";
         echo ""
-        read -rp "Resume the Debian11 VM? [Y/N]: " yn
+        read -rp "Resume the Rocky9 VM? [Y/N]: " yn
         case $yn in
-            [Yy]* ) DEBIAN="ts.debian11"; break;;
-            [Nn]* ) DEBIAN=""; break;;
+            [Yy]* ) ROCKY="ts.rocky9"; break;;
+            [Nn]* ) ROCKY=""; break;;
             [Bb]* ) clear; deploy; break;;
             * ) echo -e "\n${RED} Selection invalid, try again:${NC} "; sleep 2;;
         esac
@@ -1090,13 +1079,13 @@ resume_custom() {
         echo ""
         echo "  - CONTROL..: "${ELASTIC}" (required)"
         echo "  - target...: "${WINDOWS}""
-        echo "  - target...: "${DEBIAN}""
-        echo "  - redops...: "${REDOPS}""
+        echo "  - target...: "${ROCKY}""
+        #echo "  - redops...: "${REDOPS}""
         echo ""
         read -rp " Confirm to proceed. [Y/N]: " yn
         case $yn in
             [Yy]* )
-                vagrant resume --no-provision "${ELASTIC}" "${WINDOWS}" "${DEBIAN}" "${REDOPS}";
+                vagrant resume --no-provision "${ELASTIC}" "${WINDOWS}" "${ROCKY}";
                 sleep 10;
                 break;;
             [Nn]* ) manage; break;;
@@ -1126,7 +1115,7 @@ fi
 snapshot() {
     echo ""
     echo ""
-    for machine in elastic debian11 windows10 redops
+    for machine in elastic rocky9 windows10
     do
         vagrant snapshot save ts."${machine}" ts."${machine}"_initial;
     done
@@ -1140,7 +1129,7 @@ snapshot_restore() {
     echo ""
     echo ""
     echo "Restoring Snapshot..."
-    for machine in elastic debian11 windows10 redops
+    for machine in elastic rocky9 windows10
     do
         vagrant snapshot restore ts."${machine}" ts."${machine}"_initial
     done
@@ -1152,9 +1141,9 @@ nuke_pave() {
     echo ""
     echo -e "         ${LIGHTRED}Destruction Commencing...${NC}"
     echo ""
-    vagrant destroy -f "${ELASTIC}" "${WINDOWS}" "${DEBIAN}" "${REDOPS}";
+    vagrant destroy -f "${ELASTIC}" "${WINDOWS}" "${ROCKY}";
 
-    for machine in elastic windows10 debian11 redops
+    for machine in elastic windows10 rocky9
     do
         vagrant box remove "thremulation-station/${machine}";
     done
